# Generated by Django 3.2.6 on 2021-08-30 10:42

from django.db import migrations, models
import lookupService.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('26d15125-9181-4a77-b1cf-ed8b711e9109'), editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('text', 'Text input'), ('file', 'File upload'), ('link', 'Genome link'), ('accNum', 'Accession number')], max_length=10)),
                ('species', models.CharField(blank=True, default=lookupService.models.species_default, max_length=60)),
                ('node', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('proto', 'Protostomes'), ('deutero', 'Deuterostomes'), ('both', 'Both')], max_length=15)),
                ('dry_run', models.BooleanField(default=lookupService.models.boolean_default)),
                ('single_fam_mode', models.BooleanField(default=lookupService.models.boolean_default)),
                ('mail_address', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
