# Generated by Django 3.2.6 on 2021-11-18 12:36

from django.db import migrations, models
import lookupService.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.CharField(max_length=332, primary_key=True, serialize=False)),
                ('from_node', models.CharField(max_length=168)),
                ('to_node', models.CharField(max_length=168)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('name', models.CharField(max_length=68, primary_key=True, serialize=False)),
                ('proto', models.BooleanField(default=lookupService.models.boolean_default)),
                ('deutero', models.BooleanField(default=lookupService.models.boolean_default)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_cookie', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('halted', 'Halted')], default=lookupService.models.status_default, max_length=15)),
                ('hash', models.CharField(blank=True, max_length=168)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
                ('initiated', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('data', models.TextField(blank=True)),
                ('data_file', models.FileField(blank=True, null=True, upload_to=lookupService.models.name_uploaded_file)),
                ('mode', models.CharField(choices=[('text', 'Text input'), ('file', 'File upload'), ('accNum', 'Accession number')], max_length=10)),
                ('species', models.TextField(default=lookupService.models.species_default)),
                ('node', models.CharField(blank=True, max_length=100)),
                ('model_type', models.CharField(choices=[('proto', 'Protostomes'), ('deutero', 'Deuterostomes'), ('combined', 'Combined')], max_length=15)),
                ('single_node', models.BooleanField(default=lookupService.models.boolean_default)),
                ('single_fam_mode', models.BooleanField(default=lookupService.models.boolean_default)),
                ('family', models.CharField(blank=True, max_length=18)),
                ('mail_address', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.CharField(max_length=168, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=168)),
            ],
        ),
        migrations.CreateModel(
            name='NodeFamilyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=168)),
                ('family', models.CharField(max_length=68)),
            ],
        ),
    ]
