# Generated by Django 3.2.6 on 2021-08-30 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3cb93df9-5637-4dcd-a4f4-5af8c6050b92'), editable=False, primary_key=True, serialize=False),
        ),
    ]
