# Generated by Django 3.2.6 on 2022-05-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0002_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='thread_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
