# Generated by Django 3.2.6 on 2021-08-30 13:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0002_alter_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='initiated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f000a00-8035-4701-816b-08e1412a475c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
