# Generated by Django 3.2.6 on 2021-08-30 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0003_auto_20210830_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='data',
            field=models.CharField(default='12345', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4d01af42-2a3b-4fbd-b8a6-3adfdf7f1202'), editable=False, primary_key=True, serialize=False),
        ),
    ]
