# Generated by Django 3.2.6 on 2021-08-30 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0004_auto_20210830_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9609a65a-4739-4c23-8656-a8cc66191732'), editable=False, primary_key=True, serialize=False),
        ),
    ]
