# Generated by Django 3.2.6 on 2021-09-09 13:54

from django.db import migrations, models
import django.utils.timezone
import lookupService.models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0007_edge_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='dry_run',
            new_name='single_node',
        ),
        migrations.AddField(
            model_name='job',
            name='family',
            field=models.CharField(default=django.utils.timezone.now, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('halted', 'Halted')], default=lookupService.models.status_default, max_length=15),
        ),
    ]
