# Generated by Django 3.2.6 on 2021-09-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0008_auto_20210909_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='family',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
