# Generated by Django 3.2.6 on 2021-09-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0009_alter_job_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hash',
            field=models.CharField(blank=True, max_length=168),
        ),
    ]
