# Generated by Django 3.2.6 on 2021-09-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0010_job_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('name', models.CharField(max_length=68, primary_key=True, serialize=False)),
            ],
        ),
    ]
