# Generated by Django 3.2.6 on 2021-09-14 09:20

from django.db import migrations, models
import lookupService.models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0011_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='deutero',
            field=models.BooleanField(default=lookupService.models.boolean_default),
        ),
        migrations.AddField(
            model_name='family',
            name='proto',
            field=models.BooleanField(default=lookupService.models.boolean_default),
        ),
    ]
