# Generated by Django 3.2.6 on 2021-09-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0012_auto_20210914_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeFamilyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='lookupService.family')),
                ('node', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='lookupService.node')),
            ],
        ),
    ]
