# Generated by Django 3.2.6 on 2021-09-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0013_nodefamilyrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodefamilyrelation',
            name='family',
            field=models.CharField(max_length=68),
        ),
        migrations.AlterField(
            model_name='nodefamilyrelation',
            name='node',
            field=models.CharField(max_length=168),
        ),
    ]
