# Generated by Django 3.2.6 on 2021-09-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0014_auto_20210915_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='data',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='job',
            name='mail_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='job',
            name='node',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
