# Generated by Django 3.2.6 on 2021-09-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0015_auto_20210923_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='data',
            field=models.CharField(max_length=500000),
        ),
    ]
