# Generated by Django 3.2.6 on 2021-09-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0016_alter_job_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='data',
            field=models.TextField(),
        ),
    ]
