# Generated by Django 3.2.6 on 2021-09-24 08:37

from django.db import migrations, models
import lookupService.models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0017_alter_job_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='species',
            field=models.TextField(blank=True, default=lookupService.models.species_default),
        ),
    ]
