# Generated by Django 3.2.6 on 2021-10-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0018_alter_job_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
