# Generated by Django 3.2.6 on 2021-10-07 13:44

from django.db import migrations, models
import lookupService.models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0019_job_data_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to=lookupService.models.name_uploaded_file),
        ),
        migrations.AlterField(
            model_name='job',
            name='model_type',
            field=models.CharField(choices=[('proto', 'Protostomes'), ('deutero', 'Deuterostomes'), ('combined', 'Combined')], max_length=15),
        ),
    ]
