# Generated by Django 3.2.6 on 2021-10-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0021_auto_20211018_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='initiated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
