# Generated by Django 3.2.6 on 2021-10-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0022_alter_job_initiated'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
