# Generated by Django 3.2.6 on 2021-10-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0023_job_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user_cookie',
            field=models.TextField(blank=True),
        ),
    ]
