# Generated by Django 3.2.6 on 2021-11-03 11:03

from django.db import migrations, models
import lookupService.models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0024_job_user_cookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='mode',
            field=models.CharField(choices=[('text', 'Text input'), ('file', 'File upload'), ('accNum', 'Accession number')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='species',
            field=models.TextField(blank=True, default=lookupService.models.species_default, null=True),
        ),
    ]
