# Generated by Django 3.2.6 on 2021-11-03 11:07

from django.db import migrations, models
import lookupService.models


class Migration(migrations.Migration):

    dependencies = [
        ('lookupService', '0025_auto_20211103_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='species',
            field=models.TextField(default=lookupService.models.species_default),
        ),
    ]
