# USER CONFIG FILE, HERE YOU CAN SPECIFY DIFFERENT PARAMETERS ACCORDING TO YOUR NEEDS

MAX_NCBI_GENOME_SIZE = 100000   # In bytes

SNAKEMAKE_CPU_NUM = 4
PRINT_SNAKEMAKE_OUTPUT = True

AUTO_CLEANUP_TEMP_FILES = True

JOB_STATUS_UPDATE_FREQ = 20     # Sends update at every 100/20th percent

THROTTLE_JOB_SUBMIT = False
JOB_SUBMIT_THROTTLE_RATE = '1/m'    # 1 per minute

JOB_EXPIRATION_TIME = 7   # In days
